Geeks_Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('library.urls')),
    path('', include('hashtags.urls')),
    path('cart/', include('cart.urls')),
    path('', include('parser_kinogo.urls')),
    path('', include('recipes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import CartView, AddToCartView, RemoveFromCartView

urlpatterns = [
    path('', CartView.as_view(), name='cart_view'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove_from_cart'),
]

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.recipe_list, name='recipe_list'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/add/', views.add_recipe, name='add_recipe'),
    path('recipe/<int:recipe_id>/add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('recipe/<int:recipe_id>/delete/', views.delete_recipe, name='delete_recipe'),
]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название рецепта")
    description = models.TextField(verbose_name="Описание рецепта")

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    UNITS = [
        ("g", "граммы"),
        ("kg", "килограммы"),
        ("ml", "миллилитры"),
        ("l", "литры"),
        ("pcs", "штуки"),
    ]

    name = models.CharField(max_length=255, verbose_name="Название ингредиента")
    quantity = models.FloatField(verbose_name="Количество")
    unit = models.CharField(max_length=10, choices=UNITS, verbose_name="Единица измерения")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients")

    def __str__(self):
        return f"{self.name} ({self.quantity} {self.unit})"

recipes/forms.py
from django import forms
from .models import Recipe, Ingredient

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description']

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'quantity', 'unit', 'recipe']

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Recipe, Ingredient
from .forms import RecipeForm, IngredientForm

def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipes/recipe_list.html', {'recipes': recipes})

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    ingredients = recipe.ingredients.all()
    return render(request, 'recipes/recipe_detail.html', {'recipe': recipe, 'ingredients': ingredients})

def add_recipe(request):
    if request.method == "POST":
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipe_list')
    else:
        form = RecipeForm()
    return render(request, 'recipes/add_recipe.html', {'form': form})

def add_ingredient(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == "POST":
        form = IngredientForm(request.POST)
        if form.is_valid():
            ingredient = form.save(commit=False)
            ingredient.recipe = recipe
            ingredient.save()
            return redirect('recipe_detail', recipe_id=recipe.id)
    else:
        form = IngredientForm()
    return render(request, 'recipes/add_ingredient.html', {'form': form, 'recipe': recipe})

def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    recipe.delete()
    return redirect('recipe_list')

templates/recipes/add_ingredient.html
<h1>Добавить ингредиент к "{{ recipe.title }}"</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
<a href="{% url 'recipe_detail' recipe.id %}">Отмена</a>

templates/recipes/add_recipe.html
<h1>Добавить рецепт</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipe_list' %}">Отмена</a>

templates/recipes/recipe_detail.html
<h1>{{ recipe.title }}</h1>
<p>{{ recipe.description }}</p>

<h2>Ингредиенты</h2>
<ul>
    {% for ingredient in ingredients %}
        <li>{{ ingredient.name }} - {{ ingredient.quantity }} {{ ingredient.get_unit_display }}</li>
    {% endfor %}
</ul>

<a href="{% url 'add_ingredient' recipe.id %}">Добавить ингредиент</a>
<a href="{% url 'recipe_list' %}">Назад к списку</a>

templates/recipes/recipe_list.html
{% for recipe in recipes %}
    <h2>{{ recipe.title }}</h2>
    <p>{{ recipe.description }}</p>
    <a href="{% url 'recipe_detail' recipe.id %}">Просмотреть</a>
    <a href="{% url 'delete_recipe' recipe.id %}">Удалить</a>
{% endfor %}
<a href="{% url 'add_recipe' %}">Добавить новый рецепт</a>